server:
  port: 8989

jwt:
  secret: MzJjaGFyYWN0ZXJsb25nYmFzZTY0ZW5jb2RlZHNlY3JldGtleTEyMw==
  expiration: 86400000  # in milliseconds (1 day)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker_db
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use 'create' if you want to start fresh each time
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  # Optional logging for SQL
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
